import * as Styled from '../styles/mainStyles';
import Head from 'next/head';
import { Header } from '@/components/Header/Header';
import { Products } from '@/components/Products/Products';
import { Footer } from '@/components/Footer/Footer';
import { useGetFirstProductsQuery } from '@/context/productsApi';

export default function Home() {
  const { data, error, isLoading } = useGetFirstProductsQuery(1);

  if (error) {
    console.error(error);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Styled.Main>
        <Header />
        <Products data={data} isLoading={isLoading} />
        <Footer />
      </Styled.Main>
    </>
  );
}
